### ISSUE TITLE
Raspberry Pi Bluetooth deamon missplaced

### ISSUE THREAD

**Issue by NiiechcialA** [RobertWojtowicz/export2garmin#38]
manuals: 
    4.1.1. Preparing operating system
        sudo nano /etc/systemd/system/bluetooth.target.wants/bluetooth.service:
            ExecStart=/usr/lib/bluetooth/bluetoothd --noplugin=sap --experimental 
     --> **ExecStart=/usr/**libexec**/bluetooth/bluetoothd** --noplugin=sap --experimental

**Comment by RobertWojtowicz** [comment]
thanks, I corrected it in the manual
