### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by markist** [RobertWojtowicz/export2garmin#44]
Hi, great project! I'm close to having a usable setup (raspberry pi os, python version 3.9), however on login i get the following error:

Traceback (most recent call last):
  File "/home/martin/export2garmin-master/miscale/miscale_export.py", line 84, in <module>
    garmin.login(tokenstore)
  File "/usr/local/lib/python3.9/dist-packages/garminconnect/__init__.py", line 164, in login
    self.garth.load(tokenstore)
  File "/usr/local/lib/python3.9/dist-packages/garth/http.py", line 212, in load
    with open(os.path.join(dir_path, "oauth1_token.json")) as f:
OSError: [Errno 36] File name too long: 'VERYLONGTOKEN==/oauth1_token.json'

Any idea why?

**Comment by RobertWojtowicz** [comment]
hi, @markist

my guess is that you are using an old version of python 3.9 and/or Raspberry Pi OS - tested on the equivalent of Debian 12:
```
$ sudo uname -a
Linux RPI4B 6.6.47+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.47-1+rpt1 (2024-09-02) aarch64 GNU/Linux
$ sudo python -V
Python 3.11.2
```

BR,
Robert

**Comment by markist** [comment]
@RobertWojtowicz Thanks for replying - you were right! Went to risky way to upgrade my raspi 3B to bookworm (https://gist.github.com/jauderho/6b7d42030e264a135450ecc0ba521bd8), after setting wifi in networkmanager and reinstalling export2garmin it works like a charm!
