### ISSUE TITLE
Sync with Omron HEM-6232T - timesync not implemented yet, workaround...

### ISSUE THREAD

**Issue by floriandaur** [RobertWojtowicz/export2garmin#46]
Hi,
I tried to sync with HEM-6232T, but it failed. Found that the timesync to the omron is not yet implemented - by removing this (very dirty quick solution) I was able to sync. Maybe there is a nicer way to permantly fix this.

https://github.com/RobertWojtowicz/export2garmin/blob/0fd778e9bc9e9fb8c0cc5919c817b34ea910ef1c/omron/sharedDriver.py#L81C1-L84C156

**Comment by RobertWojtowicz** [comment]
Hi, @floriandaur

could it be a problem that i force time sync on Omron every time i take a measurement?
```python3 -B $path/omron/omblepy.py -n -t -d $omron_omblepy_model -m $omron_omblepy_mac >/dev/null 2>&1```

I can make a list of exceptions so that time synchronization is not forced, because I see that some devices e.g. HEM-7530T cannot do it: https://github.com/userx14/omblepy?tab=readme-ov-file#omron-device-support-matrix

BR,
Robert

**Comment by RobertWojtowicz** [comment]
Done, new version: https://github.com/RobertWojtowicz/export2garmin/releases

```
					# Adding an exception for selected models
					if [[ $omron_omblepy_model == "hem-6232t" ]] || [[ $omron_omblepy_model == "hem-7530t" ]]; then
						omron_flags="-n"
					else
						omron_flags="-n -t"
					fi
					if [[ $omron_omblepy_debug == "on" ]] ; then
						python3 -B $path/omron/omblepy.py -d $omron_omblepy_model --loggerDebug -m $omron_omblepy_mac
					elif [[ $omron_omblepy_all == "on" ]] ; then
						python3 -B $path/omron/omblepy.py -d $omron_omblepy_model -m $omron_omblepy_mac >/dev/null 2>&1
					else
						python3 -B $path/omron/omblepy.py $omron_flags -d $omron_omblepy_model -m $omron_omblepy_mac >/dev/null 2>&1
					fi
```
